#!/bin/bash

if [ $# -eq 0 ]; then
    echo "usage: prepare-restart <run-dir>"
    exit 1
fi

restart=$1
run=$(dirname $restart)
logfile=$run/ffe.dat
tmax=$(h5ls -dl $restart/status | tail -1 | sed 's|.*time_simulation=\([0-9]*\.*[0-9]*\).*|\1|')

echo "restart from t=$tmax with checkpoint $restart of run $run"

tmp=$(mktemp ffe.dat.XXXXXX)
bak=$(mktemp $logfile.XXXXXX)

cp $logfile $bak
cat $logfile | awk '{if ($1 < '$tmax') print }' > $tmp
mv $tmp $logfile
